name: PSuite
api-version: 1.13
version: 0.0.2.0
main: com.pencil.engine.Pencil
description: A powerful and lightweight terrain-editor for Minecraft!
website: https://github.com/Matthiaan/Pencil
author: Matthiaantje

commands:
  pencil:
    description: The main command!