name: PSuite
api-version: 1.13
version: 0.0.1.4
main: com.pencil.engine.Pencil
description: A powerful and lightweight terrain-editor for Minecraft 1.13 and up!
website: https://github.com/Matthiaan/Pencil
author: Matthiaantje

commands:
  pencil:
    description: The main command!